name: Build

on: 
    push:
        branches:
            - main
permissions:
    contents: write
    id-token: write

env:
    GAR_LOCATION : us-central1
    PROJECT_ID: project-31e386f5-2cc7-4ee4-a4b
    REPOSITORY: chat-app
    FRONTEND_IMAGE: chat-frontend
    BACKEND_IMAGE: chat-backend

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Google Auth
          uses: google-github-actions/auth@v2
          with:
            workload_identity_provider: 'projects/560553642849/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
            service_account: 'github-actions-sa@project-31e386f5-2cc7-4ee4-a4b.iam.gserviceaccount.com'

        - name: Configure Docker for GCP
          run: gcloud auth configure-docker ${{env.GAR_LOCATION}}-docker.pkg.dev --quiet
        
        - name: Build and Push To Artifacts Registry
          run: | 
            docker build -t ${{env.GAR_LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.FRONTEND_IMAGE}}:${{github.run_number}} ./frontend
            docker push ${{env.GAR_LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.FRONTEND_IMAGE}}:${{github.run_number}}

        - name: Build and Push backend To Artifacts Registry
          run: |
            docker build -t ${{env.GAR_LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.BACKEND_IMAGE}}:${{github.run_number}}  ./backend
            docker push ${{env.GAR_LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.BACKEND_IMAGE}}:${{github.run_number}}

        - name: Deploy to VM
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.VM_HOST }}
            username: ${{ secrets.VM_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              TAG=${{ github.run_number }}

              # Docker auth (important)
              gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev --quiet

              # Pull latest images
              docker pull $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$FRONTEND_IMAGE:$TAG
              docker pull $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$BACKEND_IMAGE:$TAG

              # Stop & remove old containers
              docker stop frontend || true
              docker rm frontend || true

              docker stop backend || true
              docker rm backend || true

              # Run new containers
              docker run -d -p 3001:80 --name frontend \
              $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$FRONTEND_IMAGE:$TAG

              docker run -d -p 1013:5001 --name backend \
              $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$BACKEND_IMAGE:$TAG
              
